### ISSUE TITLE
Possible to parse an url("...") inside a @font-face src declaration?

### ISSUE THREAD

**Issue by UweKeim** [AngleSharp/AngleSharp.Css#126]
Having a `@font-face` that might look like this:

```css
@font-face {
  font-family: 'Inter';
  font-style: normal;
  font-weight: 400;
  src: url(https://example.org/some-font.ttf) format('truetype');
}
```

I am able to successfully parse this to an `ICssFontFaceRule` and access the `Source` property:

```
url(https://example.org/some-font.ttf) format('truetype');
```

I'm interested in the raw value of the `url()` part:

```
https://example.org/some-font.ttf
```

Since I found no way that AngleSharp.Css might help in parsing this, I'm about to fire up some Regex to extract the URL.

Just to be extra sure that I didn't miss this functionality I'm asking this question:

Is there any built-in functionality inside AngleSharp.Css to extract the raw URL of an `url(...) ...` string?
